# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            shineMicroxy
tagline:          ''
description:      '『Coding, Traveling, Thinking, Living』'
url:              http://shinem.github.io/blog

author:
  name:           'Xinyuan'
  email:          zhongxinyuann@gmail.com

paginate:      7

# Custom vars
version:          0.0.3

# Comments

comments :
    provider : duoshuo
    duoshuo :
          short_name : zhong
