# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            shineMicroxyM
tagline:          ''
description:      '『Hi dude,my owner has no time to update me,please take me away！』'
url:              http://texy.me

author:
  name:           'Xinyuan'
  email:          zhongxinyuann@gmail.com

paginate:      6

# Custom vars
version:          0.0.3

# Comments

comments :
    provider : duoshuo
    duoshuo :
          short_name : zhong
